using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ArcadeStick.Models;

namespace ArcadeStick.Services
{
    public class CacheScannerService
    {
        private readonly ConfigurationSettings _settings;

        // =========================================================================
        // 🏁 START: LIFECYCLE AND DEPENDENCY INJECTION
        // =========================================================================
        public CacheScannerService(ConfigurationSettings settings)
        {
            _settings = settings;
        }
        // =========================================================================
        // 🛑 END: LIFECYCLE AND DEPENDENCY INJECTION
        // =========================================================================

        // =========================================================================
        // 🏁 START: ASYNCHRONOUS MAME CACHE STREAM PARSER ENGINE
        // =========================================================================
        public async Task<Dictionary<string, GameItem>> ParseCacheFileAsync(HashSet<string> discoveredZipNames, Dictionary<string, string> folderMap)
        {
            var databaseMap = new Dictionary<string, GameItem>(StringComparer.OrdinalIgnoreCase);
            // Explicitly look for the native text file output generated by mame.exe
            string cachePath = Path.Combine(_settings.GetMamePath(), "mame_cache.txt");

            if (!File.Exists(cachePath))
            {
                // Fallback mechanism to populate map from discovered physical assets if cache is missing
                foreach (var shortName in discoveredZipNames)
                {
                    folderMap.TryGetValue(shortName, out string? assignedFolder);
                    databaseMap[shortName] = new GameItem
                    {
                        RomName = shortName,
                        FullTitle = shortName.ToUpper(),
                        FolderPath = assignedFolder ?? "roms"
                    };
                }
                return databaseMap;
            }

            // Regular expression pattern mapping to capture the rom identifier and full title text (handles optional quotes)
            var lineMatcher = new Regex(@"^([a-zA-Z0-9_\-]+)\s+""?([^""]+)""?$", RegexOptions.Compiled);
            // Regex pattern to target any parenthetical blocks along with their leading whitespace
            var parentheticalMatcher = new Regex(@"\s*\([^)]*\)", RegexOptions.Compiled);

            // Stream cache index data line-by-line asynchronously to preserve background thread memory footprints
            using (var fileStream = new FileStream(cachePath, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, useAsync: true))
            using (var reader = new StreamReader(fileStream))
            {
                string? line;
                while ((line = await reader.ReadLineAsync()) != null)
                {
                    var match = lineMatcher.Match(line);
                    if (match.Success)
                    {
                        string shortName = match.Groups[1].Value.ToLower();

                        // Enforce intersection check to ensure listing only includes verified physical zip archives
                        if (discoveredZipNames.Contains(shortName))
                        {
                            folderMap.TryGetValue(shortName, out string? assignedFolder);

                            // Extract raw title, strip parenthetical clutter, and trim remaining whitespace
                            string rawTitle = match.Groups[2].Value;
                            string cleanTitle = parentheticalMatcher.Replace(rawTitle, "").Trim();

                            databaseMap[shortName] = new GameItem
                            {
                                RomName = shortName,
                                FullTitle = cleanTitle,
                                FolderPath = assignedFolder ?? "roms"
                            };
                        }
                    }
                }
            }

            return databaseMap;
        }
        // =========================================================================
        // 🛑 END: ASYNCHRONOUS MAME CACHE STREAM PARSER ENGINE
        // =========================================================================
    }
}