using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ArcadeStick.Models;

namespace ArcadeStick.Services
{
    public class CacheScannerService
    {
        private readonly ConfigurationSettings _settings;

        // [SECTION: Lifecycle & Dependency Injection]
        // Stores the shared ConfigurationSettings instance used to locate the MAME cache file.
        public CacheScannerService(ConfigurationSettings settings)
        {
            _settings = settings;
        }
        // [END SECTION: Lifecycle & Dependency Injection]

        // [SECTION: Asynchronous MAME Cache Stream Parser Engine]
        // Parses mame_cache.txt line-by-line to build a RomName -> GameItem map, filtered against
        // discoveredZipNames so only physically present ROMs are included. Falls back to a bare-bones
        // map (rom name as title) if the cache file doesn't exist yet.
        public async Task<Dictionary<string, GameItem>> ParseCacheFileAsync(HashSet<string> discoveredZipNames, Dictionary<string, string> folderMap)
        {
            var databaseMap = new Dictionary<string, GameItem>(StringComparer.OrdinalIgnoreCase);
            // Explicitly look for the native text file output generated by mame.exe
            string cachePath = Path.Combine(_settings.GetMamePath(), "mame_cache.txt");

            if (!File.Exists(cachePath))
            {
                // Fallback mechanism to populate map from discovered physical assets if cache is missing
                foreach (var shortName in discoveredZipNames)
                {
                    folderMap.TryGetValue(shortName, out string? assignedFolder);
                    databaseMap[shortName] = new GameItem
                    {
                        RomName = shortName,
                        FullTitle = shortName.ToUpper(),
                        FolderPath = assignedFolder ?? "roms"
                    };
                }
                return databaseMap;
            }

            // Regular expression pattern mapping to capture the rom identifier and full title text (handles optional quotes)
            var lineMatcher = new Regex(@"^([a-zA-Z0-9_\-]+)\s+""?([^""]+)""?$", RegexOptions.Compiled);
            // Regex pattern to target any parenthetical blocks along with their leading whitespace
            var parentheticalMatcher = new Regex(@"\s*\([^)]*\)", RegexOptions.Compiled);

            // Stream cache index data line-by-line asynchronously to preserve background thread memory footprints
            using (var fileStream = new FileStream(cachePath, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, useAsync: true))
            using (var reader = new StreamReader(fileStream))
            {
                string? line;
                while ((line = await reader.ReadLineAsync()) != null)
                {
                    var match = lineMatcher.Match(line);
                    if (match.Success)
                    {
                        string shortName = match.Groups[1].Value.ToLower();

                        // Enforce intersection check to ensure listing only includes verified physical zip archives
                        if (discoveredZipNames.Contains(shortName))
                        {
                            folderMap.TryGetValue(shortName, out string? assignedFolder);

                            // Extract raw title, strip parenthetical clutter, and trim remaining whitespace
                            string rawTitle = match.Groups[2].Value;
                            string cleanTitle = parentheticalMatcher.Replace(rawTitle, "").Trim();

                            databaseMap[shortName] = new GameItem
                            {
                                RomName = shortName,
                                FullTitle = cleanTitle,
                                FolderPath = assignedFolder ?? "roms"
                            };
                        }
                    }
                }
            }

            return databaseMap;
        }
        // [END SECTION: Asynchronous MAME Cache Stream Parser Engine]

        // [SECTION: MAME Cache File Generator]
        // Invokes mame.exe -listfull and writes the raw stdout output directly to mame_cache.txt.
        // No title cleanup occurs here; ParseCacheFileAsync already owns all stripping/formatting logic.
        public async Task GenerateCacheFileAsync()
        {
            string mamePath = _settings.GetMamePath();
            string exePath = Path.Combine(mamePath, "mame.exe");
            string cachePath = Path.Combine(mamePath, "mame_cache.txt");

            var startInfo = new ProcessStartInfo
            {
                FileName = exePath,
                Arguments = "-listfull",
                WorkingDirectory = mamePath,
                RedirectStandardOutput = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using (var process = Process.Start(startInfo))
            {
                if (process == null)
                {
                    return;
                }

                string output = await process.StandardOutput.ReadToEndAsync();
                await process.WaitForExitAsync();

                await File.WriteAllTextAsync(cachePath, output);
            }
        }
        // [END SECTION: MAME Cache File Generator]
    }
}